// カタカナを全角→半角
function zenkana2Hankana(str: string): string {
  type Kana = {
    ガ: string;
    ギ: string;
    グ: string;
    ゲ: string;
    ゴ: string;
    ザ: string;
    ジ: string;
    ズ: string;
    ゼ: string;
    ゾ: string;
    ダ: string;
    ヂ: string;
    ヅ: string;
    デ: string;
    ド: string;
    バ: string;
    ビ: string;
    ブ: string;
    ベ: string;
    ボ: string;
    パ: string;
    ピ: string;
    プ: string;
    ペ: string;
    ポ: string;
    ヴ: string;
    ヷ: string;
    ヺ: string;
    ア: string;
    イ: string;
    ウ: string;
    エ: string;
    オ: string;
    カ: string;
    キ: string;
    ク: string;
    ケ: string;
    コ: string;
    サ: string;
    シ: string;
    ス: string;
    セ: string;
    ソ: string;
    タ: string;
    チ: string;
    ツ: string;
    テ: string;
    ト: string;
    ナ: string;
    ニ: string;
    ヌ: string;
    ネ: string;
    ノ: string;
    ハ: string;
    ヒ: string;
    フ: string;
    ヘ: string;
    ホ: string;
    マ: string;
    ミ: string;
    ム: string;
    メ: string;
    モ: string;
    ヤ: string;
    ユ: string;
    ヨ: string;
    ラ: string;
    リ: string;
    ル: string;
    レ: string;
    ロ: string;
    ワ: string;
    ヲ: string;
    ン: string;
    ァ: string;
    ィ: string;
    ゥ: string;
    ェ: string;
    ォ: string;
    ッ: string;
    ャ: string;
    ュ: string;
    ョ: string;
    '。': string;
    '、': string;
    ー: string;
    '「': string;
    '」': string;
    '・': string;
    '　': string;
  };

  const kanaMap: Kana = {
    ガ: 'ｶﾞ',
    ギ: 'ｷﾞ',
    グ: 'ｸﾞ',
    ゲ: 'ｹﾞ',
    ゴ: 'ｺﾞ',
    ザ: 'ｻﾞ',
    ジ: 'ｼﾞ',
    ズ: 'ｽﾞ',
    ゼ: 'ｾﾞ',
    ゾ: 'ｿﾞ',
    ダ: 'ﾀﾞ',
    ヂ: 'ﾁﾞ',
    ヅ: 'ﾂﾞ',
    デ: 'ﾃﾞ',
    ド: 'ﾄﾞ',
    バ: 'ﾊﾞ',
    ビ: 'ﾋﾞ',
    ブ: 'ﾌﾞ',
    ベ: 'ﾍﾞ',
    ボ: 'ﾎﾞ',
    パ: 'ﾊﾟ',
    ピ: 'ﾋﾟ',
    プ: 'ﾌﾟ',
    ペ: 'ﾍﾟ',
    ポ: 'ﾎﾟ',
    ヴ: 'ｳﾞ',
    ヷ: 'ﾜﾞ',
    ヺ: 'ｦﾞ',
    ア: 'ｱ',
    イ: 'ｲ',
    ウ: 'ｳ',
    エ: 'ｴ',
    オ: 'ｵ',
    カ: 'ｶ',
    キ: 'ｷ',
    ク: 'ｸ',
    ケ: 'ｹ',
    コ: 'ｺ',
    サ: 'ｻ',
    シ: 'ｼ',
    ス: 'ｽ',
    セ: 'ｾ',
    ソ: 'ｿ',
    タ: 'ﾀ',
    チ: 'ﾁ',
    ツ: 'ﾂ',
    テ: 'ﾃ',
    ト: 'ﾄ',
    ナ: 'ﾅ',
    ニ: 'ﾆ',
    ヌ: 'ﾇ',
    ネ: 'ﾈ',
    ノ: 'ﾉ',
    ハ: 'ﾊ',
    ヒ: 'ﾋ',
    フ: 'ﾌ',
    ヘ: 'ﾍ',
    ホ: 'ﾎ',
    マ: 'ﾏ',
    ミ: 'ﾐ',
    ム: 'ﾑ',
    メ: 'ﾒ',
    モ: 'ﾓ',
    ヤ: 'ﾔ',
    ユ: 'ﾕ',
    ヨ: 'ﾖ',
    ラ: 'ﾗ',
    リ: 'ﾘ',
    ル: 'ﾙ',
    レ: 'ﾚ',
    ロ: 'ﾛ',
    ワ: 'ﾜ',
    ヲ: 'ｦ',
    ン: 'ﾝ',
    ァ: 'ｧ',
    ィ: 'ｨ',
    ゥ: 'ｩ',
    ェ: 'ｪ',
    ォ: 'ｫ',
    ッ: 'ｯ',
    ャ: 'ｬ',
    ュ: 'ｭ',
    ョ: 'ｮ',
    '。': '｡',
    '、': '､',
    ー: 'ｰ',
    '「': '｢',
    '」': '｣',
    '・': '･',
    '　': ' ',
  };

  const reg = new RegExp('(' + Object.keys(kanaMap).join('|') + ')', 'g');

  return str
    .replace(reg, function (text: string): string {
      return kanaMap[text as keyof Kana];
    })
    .replace(/゛/g, 'ﾞ')
    .replace(/゜/g, 'ﾟ');
}
export { zenkana2Hankana };
