runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
    - name: List files in the repository
      run: ls ${{ github.workspace }}
    - name: Install packages
      run: npm ci
    - name: Install Dependencies
      run: npm install